// used to sort sort colour like problems with the time constant of 
// to form the array in the form of 0,0,0,0,1,1,1,1,2,2,2
// we will devide all the spaces into three parts and then we will store the 0,1,2 into it 
// we will take first and middle as zero and last as n-1 
// we will traversse into the loop
//if we will get 2 then we will swap and end = end-1
// if we will get zero at start then both start and mid will be increased if we will get 1 then only middle will be increased


